### ISSUE TITLE
Trying to remove proxy config

### ISSUE THREAD

**Issue by barbieswimcrew** [barbieswimcrew/ddev-imgproxy#1]
As Randy Fay mentioned here https://github.com/ddev/ddev/issues/6696#issuecomment-2460006907

...using ports in docker-compose.imgproxy.yaml is not the best way because in that case only one project at a time could use this.

### Use case scenario:

A website that displays an image is running on a ddev web server. The regular path to the image is e.g. https://imgproxy.ddev.site/uploads/image.png 

Now the image is to be obtained via imgproxy, so that not the original image is delivered, but only a generated thumbnail. 

The path to the image would then be something like this:
http://localhost:8081/insecure/size:600:400/plain/uploads/image.png@avif

The imgproxy server must therefore also be “accessible” via the browser and not only exist in the Docker network.

So far, I have only been able to achieve this by configuring ports 8081:8080.

### Some attempts to solve that:
| Ports | HTTP_EXPOSE | Result |
|--------|--------|--------|
| no | no | 🟥  localhost:8080 showing `CONNECTION REFUSED` <br> 🟥  localhost:8081 showing `CONNECTION REFUSED` |
| 8081:8080 | no | 🟥  localhost:8080 showing `CONNECTION REFUSED` <br>✅  localhost:8081 showing imgproxy landing page |
| no | 8080 | 🟥  localhost:8080 showing `404 page not found` <br> 🟥  localhost:8081 showing `CONNECTION REFUSED` |
| no | 8081 | 🟥  localhost:8080 showing `CONNECTION REFUSED` <br>  🟥  localhost:8081 showing `404 page not found` | 
| no | 8081:8080 | 🟥  localhost:8080 showing `CONNECTION REFUSED` <br>  🟥  localhost:8081 showing `404 page not found` |

**Comment by stasadev** [comment]
@barbieswimcrew,

When you use expose, imgproxy can be found at `https://imgproxy.ddev.site:8081` (and `http://imgproxy.ddev.site:8080`), not at `http://localhost:8081`.

Update your `docker-compose.imgproxy.yaml` with:

```yaml
#ddev-generated
services:
  imgproxy:
    container_name: ddev-${DDEV_SITENAME}-imgproxy
    image: darthsim/imgproxy:latest
    restart: "no"
    # These labels ensure this service is discoverable by ddev.
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT
    environment:
      - IMGPROXY_BASE_URL=http://web:80/
      - IMGPROXY_ALLOW_ORIGIN="*"
      - VIRTUAL_HOST=$DDEV_HOSTNAME
      - HTTPS_EXPOSE=8081:8080
      - HTTP_EXPOSE=8080:8080
    volumes:
      - ".:/mnt/ddev_config"
      - "ddev-global-cache:/mnt/ddev-global-cache"
      - "imgproxy-cache:/imgproxy/cache"

volumes:
  imgproxy-cache:
```

And it can be accessed with:

```
ddev launch :8081/insecure/size:600:400/plain/uploads/image.png@avif
```

This can be included in a special DDEV custom command that accepts the size and path to the image.

Example of `commands/host/imgproxy`:

```
name: imgproxy
project_files:
  - docker-compose.imgproxy.yaml
  - commands/host/imgproxy
```

And:

```
#!/bin/bash

## #ddev-generated: If you want to edit and own this file, remove this line.
## Description: Launch a browser with imgproxy
## Usage: imgproxy [size] [image]
## Example: "ddev imgproxy 600:400 image.png"

size="${1:-}"
image="${2:-}"

if [ "${size}" = "" ] || [ "${image}" = "" ]; then
    ddev help imgproxy
    exit 0
fi

DDEV_IMGPROXY_PORT=8080
DDEV_IMGPROXY_HTTPS_PORT=8081

if [ ${DDEV_PRIMARY_URL%://*} = "http" ]; then
    ddev launch ":$DDEV_IMGPROXY_PORT/insecure/size:$size/plain/$image@avif"
else
    ddev launch ":$DDEV_IMGPROXY_HTTPS_PORT/insecure/size:$size/plain/$image@avif"
fi
```
